"""Agent model abstraction: deterministic fake + DeepSeek.

Graphs call ``get_model(agent)``. Tests and CI use the deterministic
``FakeModel`` (no network); production uses DeepSeek via ``langchain-openai``
when ``DEEPSEEK_API_KEY`` is set and ``AGENT_MODEL_FAKE`` is not.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Protocol

from app.core.config import get_settings

_FAKE_PAYLOADS: dict[str, dict[str, Any]] = {
    "topic": {
        "topics": [
            {"title": f"Candidate {index}", "gap": "A gap", "novelty": 7, "value": 7, "feasibility": 7, "rationale": "Promising"}
            for index in range(1, 4)
        ]
    },
    "litreview": {
        "papers": [{"title": "Paper", "authors": ["A. Author"], "year": 2024, "venue": "Venue", "findings": "Finding"}],
        "themes": ["Theme"],
        "gaps": ["Gap"],
    },
    "design": {
        "feasibility": {"score": 7, "factors": [{"name": "Data Availability", "score": 8, "note": "ok"}]},
        "hypotheses": ["H1: ..."],
        "variables": {"independent": ["IV"], "dependent": ["DV"]},
    },
    "data": {
        "scripts": [{"language": "python", "filename": "collect.py", "code": "print('ok')"}],
        "recommendations": ["Recommendation"],
        "analysisPlan": ["Clean data"],
    },
    "write": {"references": [{"key": "smith2024", "title": "Paper", "year": 2024}], "section": "introduction", "wordCount": 120},
    "submit": {"journals": [{"name": "Journal", "fitScore": 85, "impactFactor": 4.2, "reviewTimeline": "6-8 weeks", "openAccess": True}], "checklist": ["Prepare cover letter"]},
    "rebuttal": {"responses": [{"commentNumber": 1, "comment": "Comment", "response": "Response", "changeLocation": "Methods"}]},
}


@dataclass
class ModelResult:
    """Model output text plus token usage."""

    text: str
    token_in: int = 0
    token_out: int = 0


class AgentModel(Protocol):
    """Minimal async text-generation interface used by graph nodes."""

    async def generate(self, system: str, user: str) -> ModelResult: ...


class FakeModel:
    """Deterministic model returning a schema-valid JSON fence for the agent."""

    def __init__(self, agent: str) -> None:
        self.agent = agent

    async def generate(self, system: str, user: str) -> ModelResult:
        del system, user
        payload = _FAKE_PAYLOADS.get(self.agent, {})
        body = f"# {self.agent} draft\n\nGenerated by the deterministic fake model.\n"
        fence = f"```json\n{json.dumps(payload, ensure_ascii=False, indent=2)}\n```"
        return ModelResult(text=f"{body}\n{fence}", token_in=10, token_out=20)


class DeepSeekModel:
    """DeepSeek chat model via langchain-openai."""

    def __init__(self, model: str, base_url: str, api_key: str) -> None:
        from langchain_openai import ChatOpenAI

        self._llm = ChatOpenAI(model=model, base_url=base_url, api_key=api_key, temperature=0.3)

    async def generate(self, system: str, user: str) -> ModelResult:
        from langchain_core.messages import HumanMessage, SystemMessage

        response = await self._llm.ainvoke([SystemMessage(content=system), HumanMessage(content=user)])
        content = response.content if isinstance(response.content, str) else json.dumps(response.content)
        usage = getattr(response, "usage_metadata", None) or {}
        return ModelResult(
            text=content,
            token_in=int(usage.get("input_tokens", 0) or 0),
            token_out=int(usage.get("output_tokens", 0) or 0),
        )


def get_model(agent: str) -> AgentModel:
    """Return the fake model in tests/CI, else a DeepSeek model when configured."""
    settings = get_settings()
    fake = getattr(settings, "agent_model_fake", False)
    if fake or not settings.deepseek_api_key:
        return FakeModel(agent)
    model = settings.deepseek_model or "deepseek-chat"
    return DeepSeekModel(model=model, base_url=settings.deepseek_api_url, api_key=settings.deepseek_api_key)
